### ISSUE TITLE
 FDBPMpropagator crashes on MATLAB R2023b

### ISSUE THREAD

**Issue by FiodarM** [ankrh/BPM-Matlab#6]
Trying to run Example1 on MATLAB R2023b (Ubuntu 22.04 LTS) causes the error:
```
Invalid MEX-file '<...>/BPM-Matlab/+BPMmatlab/@model/private/FDBPMpropagator.mexa64': libmwboost_filesystem.so.1.75.0: cannot open shared object file: No such file or directory
Error in BPMmatlab.model/FD_BPM (line 377)
    [E,n_slice,precisePower] = FDBPMpropagator(E,mexParameters);
Error in Example1 (line 35)
P = FD_BPM(P); 
```
I recompiled the FDBPMpropagator as described in FDBPMpropagator.c, but the error remained.

I noticed that libmwboost library files in R2023b/bin/glnxa64 have  version 1.78.0, that likely the source of the error.

**Comment by ankrh** [comment]
Thanks for the bug report! I will be on vacation for about 2 weeks but will look at it when I get back.

**Comment by ankrh** [comment]
I think I have fixed the issue now. Please download the latest commit and try again. I replicated the issue and fixed it on R2024a and wasn't immediately able to test on other versions, so please reopen the issue if it doesn't work for you.
