### ISSUE TITLE
Is it possible to use the vector mode field of waveguides as the source of emission?

### ISSUE THREAD

**Issue by 694856790** [ankrh/BPM-Matlab#7]

**Comment by ankrh** [comment]
BPM matlab only solves the scalar wave equation and is less accurate in cases with large refractive index differences such as some waveguides where the vectorial field gets more relevant. You can try to let BPM matlab solve for the scalar field modes and check how accurately these modes propagate in your specific case.

**Comment by 694856790** [comment]
> BPM matlab only solves the scalar wave equation and is less accurate in cases with large refractive index differences such as some waveguides where the vectorial field gets more relevant. You can try to let BPM matlab solve for the scalar field modes and check how accurately these modes propagate in your specific case.

Can the vector mode field obtained from comsol be used for calculation?

**Comment by ankrh** [comment]
Very late response, sorry about that.

If the mode field of your guiding structure is close to being scalar then you can extract the dominant E field component from the COMSOL vector mode field and try using that in BPM-Matlab.

But I guess the reason you're choosing to use COMSOL to find vector mode fields is that the modes of your guiding structure are not well described by scalar fields, for example if the refractive index differences are not small. In that case BPM-Matlab will not accurately describe the beam propagation no matter what field you choose to initialize with.
